#!/usr/bin/env python3
"""Single source of truth for SQL → Helm chart.

`supabase/migrations/*.sql` + `supabase/seed.sql` are the canonical files.
This script mirrors them into `olares/files/` and regenerates the inlined
ConfigMap template at `olares/templates/configmap-migrations.yaml`.

CI runs this and fails if the working tree is no longer clean — that's how
we catch SQL drift between dev (`supabase/`) and prod (Olares chart).

Usage:
    python3 scripts/regen-migrations.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SUPABASE_DIR = ROOT / "supabase" / "migrations"
SEED_FILE = ROOT / "supabase" / "seed.sql"
FILES_DIR = ROOT / "olares" / "files"
TEMPLATE = ROOT / "olares" / "templates" / "configmap-migrations.yaml"


# Map source path → ConfigMap data key. Order matters — the init-container
# applies files in lexicographic order, so seed.sql comes last (0099 prefix).
SOURCES: list[tuple[Path, str]] = []


def collect_sources() -> list[tuple[Path, str]]:
    pairs: list[tuple[Path, str]] = []
    for path in sorted(SUPABASE_DIR.glob("*.sql")):
        pairs.append((path, path.name))
    if SEED_FILE.exists():
        pairs.append((SEED_FILE, "0099_seed.sql"))
    return pairs


def mirror_files(pairs: list[tuple[Path, str]]) -> None:
    FILES_DIR.mkdir(parents=True, exist_ok=True)
    # Delete stale .sql files in olares/files/ that aren't in sources.
    wanted = {key for _, key in pairs}
    # We keep the "seed" alias too: source is supabase/seed.sql but in
    # olares/files/ we historically stored it as seed.sql. Allow both names.
    wanted_alts = wanted | {"seed.sql"}
    for existing in FILES_DIR.glob("*.sql"):
        if existing.name not in wanted_alts:
            print(f"  removing stale {existing.relative_to(ROOT)}")
            existing.unlink()
    # Copy current sources.
    for src, key in pairs:
        # supabase/seed.sql → olares/files/seed.sql (legacy name kept)
        target_name = "seed.sql" if key == "0099_seed.sql" else key
        dst = FILES_DIR / target_name
        shutil.copyfile(src, dst)


def render_configmap(pairs: list[tuple[Path, str]]) -> str:
    header = (
        '# ============================================================================\n'
        '# ConfigMap: SQL migration & seed files.\n'
        '#\n'
        '# AUTO-GENERATED by scripts/regen-migrations.py.\n'
        '# DO NOT EDIT this file by hand. Edit supabase/migrations/*.sql or\n'
        '# supabase/seed.sql instead, then re-run the generator.\n'
        '#\n'
        '# Mounted into the backend Deployment\'s `migrate` init-container, which\n'
        '# runs them via asyncpg with a retry loop. We can\'t use Helm hooks here\n'
        '# because the `bytetrade.io/ns-owner` namespace label that the DB\'s\n'
        '# NetworkPolicy keys on is only set AFTER `helm install` completes —\n'
        '# so a post-install hook can never reach the DB. The init-container\n'
        '# pattern sidesteps that: the pod just keeps restarting until the\n'
        '# label is set.\n'
        '#\n'
        '# SQL is inlined (rather than via `.Files.Get`) because Olares\' chart\n'
        '# renderer doesn\'t expose `.Files`.\n'
        '# ============================================================================\n'
        '\n'
        'apiVersion: v1\n'
        'kind: ConfigMap\n'
        'metadata:\n'
        '  name: insilo-migrations\n'
        '  namespace: {{ .Release.Namespace }}\n'
        '  labels:\n'
        '    app: insilo\n'
        '    component: migrations\n'
        'data:\n'
    )
    body = []
    for src, key in pairs:
        content = src.read_text()
        # YAML literal block: indent every line by 4 spaces beneath `key: |`.
        indented = "\n".join("    " + line if line else "    " for line in content.split("\n"))
        body.append(f"  {key}: |\n{indented}\n")
    return header + "".join(body)


def main() -> int:
    pairs = collect_sources()
    if not pairs:
        print("ERROR: no SQL files found", file=sys.stderr)
        return 1

    print(f"Sources: {len(pairs)} file(s) from supabase/")
    for _, key in pairs:
        print(f"  - {key}")

    print("Mirroring into olares/files/...")
    mirror_files(pairs)

    print("Rendering olares/templates/configmap-migrations.yaml...")
    rendered = render_configmap(pairs)
    TEMPLATE.write_text(rendered)
    print(f"  wrote {len(rendered):,} bytes")

    return 0


if __name__ == "__main__":
    sys.exit(main())
